### ISSUE TITLE
Task: Enviromental Adaptation 1

### ISSUE THREAD

**Issue by caranha** [Megacruxis/UrbanSettlementGenerator#2]
After adding a new building type, modify it so that it adapts to the environment: The blocks used in the building change depending the types of original blocks existing around.

Make sure to take screenshots of the results of the filter!

**Comment by Megacruxis** [comment]
Have a first layer of adaptability. Will now try to modify the block used for the construction with the biome (like in desert the green house would use yellow glass instead of white glass and sandstone instead of grass path).
